#!/bin/bash

#
# Clone IDX/IIS GitHub repositories
#

METHOD=https
CLONE_V2=true
CLONE_V1=true
CLONE_WEB=true
CLONE_IIS=true

usage() {
cat <<- EOF
USAGE: git-clone-idx [[-h|--help]] | [--https|-ssh] [--all|--none] [--v2|--no-v2] 
     [--v1|--no-v1] [--web|--no-web] [--iis|--no-iis]]

From WORKDIR, clone the IDX GitHub repositories (if not already existing).

OPTIONS:
	--https       use 'https' method of cloning repositories (default)
	--ssh         use 'ssh' method of cloning repositories
	--all         clone all repositories (V1, V2, web, IIS; default)
	--none        clone no repositories (used first to specify specific modules)
	--v2          clone IDX V2 repositories
	--no-v2       do not clone IDX V2 repositories
	--v1          clone IDX V1 repositories
	--no-v1       do not clone IDX V1 repositories
	--web         clone IDX web repositories
	--no-web      do not clone IDX web repositories
	--iis         clone IIS repository
	--no-iis      do not clone IIS repository
	-h | --help   display this help
EOF
}

while :
do
	case "$1" in
		--http)
			METHOD=https
			shift
			;;
		--ssh)
			METHOD=ssh
			shift
			;;
		--all)
			CLONE_V1=true
			CLONE_V2=true
			CLONE_WEB=true
			CLONE_IIS=true
			shift
			;;
		--none)
			CLONE_V1=false
			CLONE_V2=false
			CLONE_WEB=false
			CLONE_IIS=false
			shift
			;;
		--v2)
			CLONE_V2=true
			shift
			;;
		--no-v2)
			CLONE_V2=false
			shift
			;;
		--v1)
			CLONE_V1=true
			shift
			;;
		--no-v1)
			CLONE_V1=false
			shift
			;;
		--web)
			CLONE_WEB=true
			shift
			;;
		--no-web)
			CLONE_WEB=false
			shift
			;;
		--iis)
			CLONE_IIS=true
			shift
			;;
		--no-iis)
			CLONE_IIS=false
			shift
			;;
		-h | --help)
			usage
			exit 1
			;;
		--)         # end of all options
			shift
			break
			;;
		*)          # no more options
			break
			;;
	esac
done

cd $WORKDIR

REPOS_IIS="iis"

cloneHTTP() {
	for REPO in $*
	do
		if [[ ! -d $REPO ]]; then
			git clone https://github.com/fs-eng/$REPO.git
		fi
	done
}

cloneSSH() {
	for REPO in $*
	do
		if [[ ! -d $REPO ]]; then
			git clone git@github.com/fs-eng/$REPO.git
		fi
	done
}

if [[ "$METHOD" == "https" ]]; then
	if $CLONE_V2; then
		cloneHTTP $IDX_V2_PROJECTS
	fi
	if $CLONE_V1; then
		cloneHTTP $IDX_V1_PROJECTS
	fi
	if $CLONE_WEB; then
		cloneHTTP $IDX_WEB
	fi
	if $CLONE_IIS; then
		cloneHTTP $REPOS_IIS
	fi
else
	if $CLONE_V2; then
		cloneSSH $IDX_V2_PROJECTS
	fi
	if $CLONE_V1; then
		cloneSSH $IDX_V1_PROJECTS
	fi
	if $CLONE_WEB; then
		cloneSSH $IDX_WEB
	fi
	if $CLONE_IIS; then
		cloneSSH $REPOS_IIS
	fi
fi
