#!/bin/bash

#
# From WORKDIR, this recursively enters the IDX git
# repositories and reports on the current checked out
# branch.
#

pushd $WORKDIR

for DIR in $IDX_ALL
do
	echo ========================
	echo PROJECT - $DIR
	cd $DIR
	git branch
	cd ..
done

popd
