#!/bin/bash

#
# From WORKDIR, this script recursively enters all IDX
# git repositories and performs a 'git fetch'.
#

usage() {
cat <<- EOF
USAGE: git-idx-fetch [[-h|--help] | [-p|--prune] | [--dry-run]]

From WORKDIR, enter all IDX repository directories and perform a 'git fetch'.

OPTIONS:
   -h | --help   display this help
   -p | --prune  prune local remote branch references
   --dry-run	 dry-run the prune action
EOF
}

OPTIONS=

while :
do
	case "$1" in 
		-p | --prune)
			OPTIONS="$OPTIONS --prune"
			shift
			;;
		--dry-run)
			OPTIONS="$OPTIONS --dry-run"
			shift
			;;
		-h | --help)
			usage
			exit 1
			;;
		--)			# end of all options
			shift
			break
			;;
		*)			# no more options
			break
			;;
	esac
done

pushd $WORKDIR

for DIR in $IDX_ALL
do
	echo ========================
	echo PROJECT - $DIR \(OPTIONS: $OPTIONS\)
	cd $DIR
	git fetch $OPTIONS
	cd ..
done

popd
