#!/bin/bash

#
# From WORKDIR, this script recursively enters all IDX
# git repositories and reports on the 'git status'.
#

pushd $WORKDIR

for DIR in $IDX_ALL
do
	echo ========================
	echo PROJECT - $DIR
	cd $DIR
	RESULT=`git status`
	PREFIX=
	POSTFIX=
	if [[ $RESULT != *"master"* ]]
	then
		PREFIX='\e[1;33m'
		POSTFIX='\e[0m'
	elif [[ $RESULT != *"up-to-date"* ]]
	then
		PREFIX='\e[1;34m'
		POSTFIX='\e[0m'
	fi
	echo -e $PREFIX$RESULT$POSTFIX
	cd ..
done

popd
