#!/bin/bash

#
# From WORKDIR, this recursively enters the IDX git
# repositories and deletes merged branches.
#

usage() {
cat <<- EOF
USAGE: git-idx-clean-merged [[-h|--help]]

From WORKDIR, enter all IDX repository directories and 
delete merged branches.

OPTIONS:
   -h | -- help     display this help
EOF
}

while :
do
    case "$1" in
        -h | --help)
            usage
            exit 1
            ;;
        --)         # end of all options
            shift
            break
            ;;
        *)          # no more options
            break
            ;;
    esac
done

pushd $WORKDIR

for DIR in $IDX_ALL
do
	echo ========================
	echo PROJECT - $DIR
	cd $DIR
	git branch --merged | grep -v master | xargs git branch -d 
	cd ..
done

popd
