#!/bin/bash 

set -e

usage() {
	cat <<- EOF
USAGE: git-idx-update-verticals [[-h|--help]] | [-l|--local] [-p|--pause] [--v1] [-k | --keep] | [[-f|--from] <project>]

From WORKDIR, enter all IDX_V2_VERTICALS and update the versions
via the 'git-mvn-versions' command.

OPTIONS:
   -p | --pause     pause in each repo to allow for acceptance tests
   -l | --local     make only local repo changes; i.e., don't 
                    push the modified branch to the remote repos
   -k | --keep      keep the git branch rather than deleting it
   --v1             include V1 projects
   -f | --from <project>  continue the update from the specified project,
                          skipping previous projects   
   -h | --help      display this help
EOF
}

REPOS=$IDX_V2_VERTICALS

while :
do
    case "$1" in
        -p | --pause)
            MY_OPTIONS="$MY_OPTIONS --pause"
            shift
            ;;
		-l | --local)
			MY_OPTIONS="$MY_OPTIONS --local"
			shift
			;;
		--v1)
			REPOS="$IDX_V1_PROJECTS $REPOS"
			shift
			;;
        -k | --keep)
            MY_OPTIONS="$MY_OPTIONS --keep"
            shift
            ;;
		-f | --from)
			FROM="$2"
			shift 2
			;;			
        -h | --help)
            usage
            exit 1
            ;;
        --)         # end of all options
            shift
            break
            ;;
        *)          # no more options
            break
            ;;
    esac
done

do_mvn_update() 
{
	SKIP=N
	if [ ! -z "$FROM" ]
	then
		SKIP=Y
	fi

	for PROJECT
	do
		echo ========================
		echo PROJECT - $PROJECT
		
		if [ $SKIP == "Y" -a $PROJECT != "$FROM" ]
		then
			echo Skipping $PROJECT	
		else
			SKIP=N
			cd $PROJECT
			git-mvn-versions $MY_OPTIONS
			cd ..
		fi
	done
}

pushd $WORKDIR

time do_mvn_update $REPOS

popd