#!/bin/bash

set -e 

#
# From the current directory, checkout a "pull-request" 
# branch from GitHub, build the project, and start the 
# server (if applicable).
#

usage() {
cat <<- EOF
USAGE: git-verify-pr [[-h|--help]] <PR #>

From CURRENTDIR, checkout a "pull-request" branch from 
GitHub and build the project. If applicable, this will 
start the 'acceptance' module.

OPTIONS:
   -h | -- help     display this help
EOF
}

while :
do
    case "$1" in
        -h | --help)
            usage
            exit 1
            ;;
        --)         # end of all options
            shift
            break
            ;;
        *)          # no more options
            break
            ;;
    esac
done

PR=$1

git fetch origin
git checkout pr/$PR
mvn -T 1C clean install 
if [ -d acceptance ]; then
	cd acceptance
	mvn cargo:run 
	cd ..
fi
