#!/bin/bash

usage() {
	cat <<- EOF
USAGE: git-mvn-spike [[-h|--help]]

From the current directory, create a local spike branch and update the parent pom
to use the local SNAPSHOT versions of the super pom and other libraries.

OPTIONS:
   -h | --help     display this help
EOF
}

while :
do
    case "$1" in
        -h | --help)
            usage
            exit 1
            ;;
        --)         # end of all options
            shift
            break
            ;;
        *)          # no more options
            break
            ;;
    esac
done


git checkout -b spike
xmlstarlet ed -L -P -u //_:parent/_:version -v 1.2-SNAPSHOT pom.xml
xmlstarlet ed -L -P -u //_:idx-api-core.version -v 2.2-SNAPSHOT pom.xml
xmlstarlet ed -L -P -u //_:idx-api-domain.version -v 2.2-SNAPSHOT pom.xml
xmlstarlet ed -L -P -u //_:idx-db-migration.version -v 1.0-SNAPSHOT pom.xml
