#!/bin/bash

set -e

usage() {
cat <<- EOF
USAGE: mvn-idx-build [[-h|--help]] | [[-f|--from] <project>]

From WORKDIR, this script will perform a Maven build for all IDX repositories.

OPTIONS:
   -f | --from <project>  continue the build from the specified project,
                          skipping previous projects
   -h | -- help           display this help						  
EOF
}

while :
do
	case "$1" in
		-f | --from)
			FROM="$2"
			shift 2
			;;
		-h | --help)
			usage
			exit 1
			;;
		--) 		# end of all options
			shift
			break
			;;
		*) 			# no more options
			break
			;;
	esac
done

do_mvn_build()
{
	SKIP=N
	if [ ! -z "$FROM" ]
	then
		SKIP=Y
	fi
	
	for PROJECT
	do
		if [ $SKIP == "Y" -a $PROJECT != "$FROM" ]
		then
			echo Skipping $PROJECT
		else
			SKIP=N
			cd $PROJECT
			mvn clean install
			cd ..
		fi
	done
}

pushd $WORKDIR

time do_mvn_build $IDX_ALL

popd