#!/bin/bash

#
# From the CURRENTDIR, update parent POM version and 
# property versions to the latest found in the remote
# repository
#

set -e 

mvn -U versions:update-parent versions:update-properties versions:commit
