#!/bin/bash

#
# From the CURRENTDIR, do a clean Maven build. If the project is an
# application, it will start the acceptance module and server.
#

set -e 

usage() {
cat <<- EOF
USAGE: mvn-build [-o | --offline]

From the CURRENTDIR, do a clean Maven build. If the project is an
application, it will start the acceptance module and server.

OPTIONS:
   -o | --offline 	execute Maven offline
   -h | -- help     display this help
EOF
}

OPTIONS="-T 1C"

while :
do
    case "$1" in
        -o | --offline)
            OPTIONS="$OPTIONS -o"
            shift
            ;;
        -h | --help)
            usage
            exit 1
            ;;
        --)         # end of all options
            shift
            break
            ;;
        *)          # no more options
            break
            ;;
    esac
done


mvn $OPTIONS clean install 

if [[ -d acceptance ]]
then
	cd acceptance
	mvn $OPTIONS cargo:run
	cd ..
fi
